### ISSUE TITLE
使用PySide6的QSql模块连接mysql问题

### ISSUE THREAD

**Issue by yonglih** [sunshe35/PySide6-codes#1]
有尝试过使用PySide6的QSql模块连接mysql吗？代码里面只看到连接SQLite数据库，换成mysql就不行了。

**Comment by sunshe35** [comment]
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/sunshe35/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

<link rel=themeData
href="file:///C:/Users/sunshe35/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/sunshe35/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=ZH-CN style='tab-interval:21.0pt;text-justify-trim:punctuation'>




数据库驱动类型 | 描    述
-- | --
QDB2 | IBM DB2（7.1及以上版本）
QMYSQL/MARIADB | MySQL或MariaDB（5.6及以上版本）
QOCI | Oracle调用接口驱动程序（12.1及以上版本）
QODBC | 开放式数据库连接（ODBC）：Microsoft   SQL Server和其他兼容ODBC的数据库
QPSQL | PostgreSQL（7.3及以上版本）
QSQLITE | SQLite 3




</body>

</html>


有的，具体用法参见 章节 “5.10.2 连接数据库”。页码大概P386页。

**Comment by yonglih** [comment]
电子书上没有5.10.2的章节呢？

**Comment by yonglih** [comment]
> <style> </style>
> 数据库驱动类型	描    述
> QDB2	IBM DB2（7.1及以上版本）
> QMYSQL/MARIADB	MySQL或MariaDB（5.6及以上版本）
> QOCI	Oracle调用接口驱动程序（12.1及以上版本）
> QODBC	开放式数据库连接（ODBC）：Microsoft SQL Server和其他兼容ODBC的数据库
> QPSQL	PostgreSQL（7.3及以上版本）
> QSQLITE	SQLite 3
> 有的，具体用法参见 章节 “5.10.2 连接数据库”。页码大概P386页。

电子书上没有5.10.2的章节呢？

**Comment by sunshe35** [comment]
> > <style> </style>
> > 数据库驱动类型	描    述
> > QDB2	IBM DB2（7.1及以上版本）
> > QMYSQL/MARIADB	MySQL或MariaDB（5.6及以上版本）
> > QOCI	Oracle调用接口驱动程序（12.1及以上版本）
> > QODBC	开放式数据库连接（ODBC）：Microsoft SQL Server和其他兼容ODBC的数据库
> > QPSQL	PostgreSQL（7.3及以上版本）
> > QSQLITE	SQLite 3
> > 有的，具体用法参见 章节 “5.10.2 连接数据库”。页码大概P386页。
> 
> 电子书上没有5.10.2的章节呢？

![Screenshot_20230215_202213_com tencent mm](https://user-images.githubusercontent.com/16757906/219027270-31b8ebe6-83ff-4608-98a9-604b85986f58.jpg)
我这里显示有啊，稍后会上传目录。
